### ISSUE TITLE
Finalize the Jakarta Connectors 2.1 Release

### ISSUE THREAD

**Issue by ivargrimstad** [jakartaee/connectors#134]
Please complete these steps to finalize the release:
- [x] promotes api staging release promotes the specification api jars to maven central. An example release job script can be found here https://wiki.eclipse.org/MavenReleaseScript.
 - [x] go through the merged jakarta.ee specification website page to verify all the links are valid.
 - [ ] if XML Schemas are published on https://jakarta.ee/schemas, send a PR to update the status from `Draft` to `Final`.
 - [x] approve the compatibility request.
 - [x] The compatible implementation project/vendor MUST send an email to tck@eclipse.org for approval of the compatible implementation for trademark usage.
 - [x] merge any final release branch as appropriate for the branch management for the project.

**Comment by pzygielo** [comment]
Hello Connectors Team,

May I ask to have api jar released to Central, please?

**Comment by smillidge** [comment]
It is released now on jakarta.oss so will propagate over to central at some point soon.

**Comment by pzygielo** [comment]
:tada: Thank you!

**Comment by arjantijms** [comment]
I guess this can be closed now?
