### ISSUE TITLE
Move this repo to https://github.com/jakartaee 

### ISSUE THREAD

**Issue by arjantijms** [jakartaee/connectors#135]
In the steering committee we voted to moved all specification projects from eclipse-ee4j to jakartaee. As such this repo should move to in due time.

Moving is fairly automatic, and redirects will be automatically put in place from the current location here to the new location.

If someone can authorise the move I can take care of it if needed.

Extra from: https://www.eclipse.org/lists/jakarta.ee-spec/msg02073.html

"We voted on it in 2019 and then in 2020 we added it explicitly to our 2021 plan and voted on that plan.  I think we just need to start executing.  I sent about 30 emails like the following in an attempt to add some shape to it and kick off the move in the spec projects. 

 - https://www.eclipse.org/lists/jakartaee-platform-dev/msg02940.html
 - https://www.eclipse.org/lists/messaging-dev/msg00028.html
 - https://www.eclipse.org/lists/jakartaee-tck-dev/msg01417.html
 - https://www.eclipse.org/lists/ejb-dev/msg00264.html
"

Also note that many projects have indeed moved: https://github.com/jakartaee/

**Comment by jgallimore** [comment]
I'm ok with it. Is there a specific process in order to authorise it? Anything I can do to help?

**Comment by njr-11** [comment]
+1 this is an excellent time within the release schedule to move repositories

**Comment by arjantijms** [comment]
> I'm ok with it. Is there a specific process in order to authorise it? Anything I can do to help?

There's no help for now needed, I just started the process of moving. After the move, it would be good practice to update all jobs on the CI (http://ci.eclipse.org/jca) to point to the new location. Redirects are put in place automatically, but to prevent any issues with plugins that may not like redirects it's best to update the locations.

**Comment by arjantijms** [comment]
@jgallimore the move has been done, if you want can you update any jobs that refer to the old location?
